name: Demo GitHub Actions Events
run-name: wwwwwwwwwwwwwwww

on:
  # Webhook
  push:
    branches:
      - main
      - master
      - demo-*
  pull_request:
    branches:
      - main
      - master
  issues:
    types:
      - opened
      - closed
  schedule:
    - cron: 0 0 0 0 0

  # Manual events
  workflow_dispatch:
    inputs:
      param1:
        description: Provide param1
        required: true
        default: default_param1
      param2:
        description: Provide param2
        required: true
        type: boolean
      param3:
        description: Provide param3
        required: true
        type: choice
        options:
          - choice1
          - choice2
          - choice3
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "This is job1 step1"
      - name: inputs1
        run: echo param1 ${{ inputs.param1}}
      - name: input2
        run: echo "param2 ${{ inputs.param2}}"
      - name: input3
        run: echo 'param3 ${{ inputs.param3}}'
        