name: Demo GitHub Actions Events
run-name: wwwwwwwwwwwwwwww

on:
  # Webhook
  push:
    branches:
      - main
      - master
      - demo-*
  pull_request:
    branches:
      - main
      - master
  issues:
    types:
      - opened
      - closed

  workflow_dispatch:
    inputs:
      param1:
        description: Provide param1
        required: true
        default: default_param1

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      LOCATION: SE3
    steps:
      - name: conditional1
        run: echo "param is CAT"
        if: ${{ inputs.param1 == 'cat' }}
      - name: conditional2
        run: echo "param is DOG"
        if: ${{ inputs.param1 == 'dog' }}
      - name: location
        run: echo ${{ env.LOCATION }}

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github event context
        run: echo '${{ toJson(github.event) }}'
      - name: Dump runner context
        run: echo '${{ toJson(runner) }}'
